# Generated by Django 5.2.3 on 2025-06-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Blood', models.CharField(default='', max_length=20)),
                ('Date', models.DateField()),
            ],
        ),
    ]
