# Generated by Django 5.2.3 on 2025-07-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toto', '0002_det_delete_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='det',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='det',
            name='message',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='det',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='det',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
