# Generated by Django 5.2.3 on 2025-07-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toto', '0003_det_email_det_message_alter_det_id_alter_det_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='donor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='', max_length=200)),
                ('middlename', models.CharField(default='', max_length=200)),
                ('lastname', models.CharField(default='', max_length=200)),
                ('gender', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('bloodgroup', models.CharField(default='', max_length=200)),
                ('image', models.FileField(default='', upload_to='toto/image')),
                ('phone', models.IntegerField(default=0)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=200)),
                ('confirm_password', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='receipent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='', max_length=200)),
                ('middlename', models.CharField(default='', max_length=200)),
                ('lastname', models.CharField(default='', max_length=200)),
                ('gender', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('bloodgroup', models.CharField(default='', max_length=200)),
                ('image', models.FileField(default='', upload_to='toto/image')),
                ('phone', models.IntegerField(default=0)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
