# Generated by Django 5.2.3 on 2025-07-02 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toto', '0004_donor_receipent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='confirm_password',
        ),
    ]
