# Generated by Django 5.2.3 on 2025-07-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toto', '0005_remove_donor_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='image',
            field=models.FileField(default='', upload_to='media/toto/image'),
        ),
    ]
