# Generated by Django 5.2.3 on 2025-07-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toto', '0006_alter_donor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='image',
            field=models.FileField(default='', upload_to='toto/image'),
        ),
    ]
