# Generated by Django 5.2.3 on 2025-07-02 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toto', '0007_alter_donor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipent',
            name='password',
        ),
    ]
